// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"
	api "practice-golang/inventory/api"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ClientAdapter is an autogenerated mock type for the ClientAdapter type
type ClientAdapter struct {
	mock.Mock
}

// GetQuantity provides a mock function with given fields: ctx, in, opts
func (_m *ClientAdapter) GetQuantity(ctx context.Context, in *api.GetQuantityRequest, opts ...grpc.CallOption) (*api.GetQuantityResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *api.GetQuantityResponse
	if rf, ok := ret.Get(0).(func(context.Context, *api.GetQuantityRequest, ...grpc.CallOption) *api.GetQuantityResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetQuantityResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.GetQuantityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateQuantity provides a mock function with given fields: ctx, in, opts
func (_m *ClientAdapter) UpdateQuantity(ctx context.Context, in *api.UpdateQuantityRequest, opts ...grpc.CallOption) (*api.UpdateQuantityResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *api.UpdateQuantityResponse
	if rf, ok := ret.Get(0).(func(context.Context, *api.UpdateQuantityRequest, ...grpc.CallOption) *api.UpdateQuantityResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.UpdateQuantityResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.UpdateQuantityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClientAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientAdapter creates a new instance of ClientAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientAdapter(t mockConstructorTestingTNewClientAdapter) *ClientAdapter {
	mock := &ClientAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
