// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package orders

import ()

type Order struct {
	ID       int32  `json:"id"`
	Sku      string `json:"sku"`
	Quantity int32  `json:"quantity"`
}
