// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: orders_queries.sql

package orders

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  id, sku, quantity
) VALUES (
  $1, $2, $3
)
RETURNING id, sku, quantity
`

type CreateOrderParams struct {
	ID       int32  `json:"id"`
	Sku      string `json:"sku"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.ID, arg.Sku, arg.Quantity)
	var i Order
	err := row.Scan(&i.ID, &i.Sku, &i.Quantity)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, sku, quantity FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.Sku, &i.Quantity)
	return i, err
}

const listOrder = `-- name: ListOrder :many
SELECT id, sku, quantity FROM orders
ORDER BY id
`

func (q *Queries) ListOrder(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.Sku, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
set sku = $2,
quantity = $3
WHERE id = $1
RETURNING id, sku, quantity
`

type UpdateOrderParams struct {
	ID       int32  `json:"id"`
	Sku      string `json:"sku"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrder, arg.ID, arg.Sku, arg.Quantity)
	var i Order
	err := row.Scan(&i.ID, &i.Sku, &i.Quantity)
	return i, err
}
