// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: create_product.sql

package inventory

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO inventory (
    sku,
    quantity
) VALUES (
    $1, $2
)
RETURNING sku, quantity
`

type CreateProductParams struct {
	Sku      string `json:"sku"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Sku, arg.Quantity)
	var i Inventory
	err := row.Scan(&i.Sku, &i.Quantity)
	return i, err
}
